sudo: false
language: go
go:
- 1.5.3
env:
- PATH=/home/travis/gopath/bin:$PATH
before_install:
- go get github.com/mitchellh/gox
- go get github.com/tcnksm/ghr
script:
- go get ./... && go build && go test ./...
after_success:
- gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
- ghr --username boivie --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
